services:
  scrapper:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://public_procurements_db/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

      PROCUREMENT_SCRAPE_ALL: ${PROCUREMENT_SCRAPE_ALL:-false}
      PROCUREMENT_FIRST_DATE_OF_PUBLICATION: ${PROCUREMENT_FIRST_DATE_OF_PUBLICATION:-2022-01-01}
      PROCUREMENT_PAGES_PER_FETCH: ${PROCUREMENT_PAGES_PER_FETCH:-5}
    env_file:
      - .env

  database:
    image: postgres:14-alpine
    restart: always
    container_name: public_procurements_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  pg_data: