services:
  scrapper:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://public_procurements_db/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

      RUN_ON_STARTUP: ${RUN_ON_STARTUP:-true}
      SCHEDULING_CRON: ${SCHEDULING_CRON:-0 0 0 1 * *}
    env_file:
      - .env

  database:
    image: postgres:14-alpine
    restart: always
    container_name: public_procurements_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  pg_data:
  grafana-storage:
