services:
  scrapper:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: scrapper
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://public_procurements_db/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      - RUN_ON_STARTUP=true
      - SCHEDULING_CRON=0 0 0 1 * *
      - SCRAPE_ALL=true
      - CORE_POOL_SIZE=5
    env_file:
      - .env

  database:
    image: postgres:14-alpine
    restart: always
    container_name: public_procurements_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: database_viewer
    restart: always
    ports:
      - 8081:8080

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  pg_data:
  grafana-data:
  prometheus-data:
